### PR TITLE
Disable escaping from service short description

### PR DESCRIPTION
**Pull request by humble-ahitofel**
See the issue for more information: https://projektit.kirjastot.fi/issues/5729

### CODE REVIEW

**Comment by humble-ahitofel** [comment]
It seems that API outputs HTML content in the output: http://api.kirjastot.fi/v4/library?id=85142&with=services   (see "Kahvilat" service)
Yeah I agree, that the best thing would be no HTML content in short description at all, but libraries have used it to put some links etc. and now Finna is using it in their api. So basically the request here was that the public hakemisto directory would also output the html content in the 'short description' field.
One option of course would be to change, that the API  also would not output any HTML in the aforementioned field, but I have to ask finna about this then.

**Comment by sjuvonen** [comment]
The widgets still need to be adapted to this change...

**Comment by humble-ahitofel** [comment]
After discussing this with Antti, it seems this needs some further work. The field is now incorrectly used, and the fix should be applied else where. (http://api.kirjastot.fi/  section 2.4 mention only few field that have HTML content)

I'm closing this pull request.

**Comment by sjuvonen** [comment]
If you don't want to enable HTML in the field, it is possible to use
StripTags filter to scrap them. This method was used with some other field
because libraries abused the old version of Kirkanta with Helmet.fi.

**Pull request closed without merging**
